# Generated by Django 3.1 on 2021-09-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20210911_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(default='test', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='tap_charge_id',
            field=models.CharField(default='test', max_length=500),
            preserve_default=False,
        ),
    ]
