# Generated by Django 3.1 on 2021-09-20 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20210911_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='tap_token_id',
            new_name='tap_authorization_id',
        ),
    ]
