# Generated by Django 3.1 on 2021-09-20 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20210906_0846'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0005_auto_20210920_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='tap_authorization_id',
            new_name='tap_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='tap_charge_id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_related_payments', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_related_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
