# Generated by Django 3.1 on 2022-01-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_payment_tap_refund_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
