deploy:
  stage: deploy
  only:
    - master
  script:
    - cd ..
    - apt-get update
    - apt-get install sshpass
    - pwd
    - tar -czf backend.tgz wtd-backend
    - cd wtd-backend/
    - bash deploy.sh $PASSWORD

#deploy-master:
#  stage: deploy
#  only:
#    - master
#  variables:
#    VERSION: $CI_COMMIT_TAG
#  script:
#    - echo $VERSION
#    - apt-get update
#    - cd ..
#    - apt-get install sshpass
#    - tar -czf backend.tgz backend
#    - cd backend/
#    - bash docker-login.sh $PASSWORD $DOCKER_USER $DOCKER_PASSWORD v0.0.6