version: '3.3'
services:
  db:
    image: postgres
    container_name: database
    restart: always
    environment:
      - "POSTGRES_PASSWORD=postgresPass"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=postgres"
    ports:
      - 5432:5432
    volumes:
      - type: volume
        source: database-data
        target: /var/lib/postgresql/data
  backend:
    build: ./wtd-backend
    container_name: backend
    restart: always
    ports:
      - "1234:8000"
    environment:
      - "USER_EMAIL=support@pubbles.app"
      - "USER_EMAIL_PASSWORD=PubblesP@$$$$w0rdSupport"
      - "database=postgres"
      - "username=postgres"
      - "password=postgresPass"
    volumes:
      - type: volume
        source: django-static
        target: /code/static
      - type: volume
        source: django-uploads
        target: /code/media/
    links:
      - redis
    depends_on:
      - db
  redis:
    image: "redis:alpine"
    restart: always
    ports:
        - "6379:6379"
  nginx:
    build: ./wtd-backend/nginx/
    container_name: nginx
    volumes:
      - type: volume
        source: wtd-nginx
        target: /etc/nginx/conf.d/
      - "/var/lib/docker/volumes/wtd_django-static/_data/:/usr/share/nginx/html/static/"
      - "/etc/letsencrypt/live/wtd.care/cert.pem:/cert.pem"
      - "/etc/letsencrypt/live/wtd.care/privkey.pem:/privkey.pem"
    # - /root/wtd/wtd-backend/nginx/default.conf:/etc/nginx/conf.d/
    ports:
        - "80:80"         
        - "443:443" 
volumes:
  django-static:
  django-uploads:
  database-data:
  wtd-nginx: