version: '3.3'
services:
  nginx:
    build: ./wtd-backend/nginx/
    container_name: nginx
    ports:
      - "80:80"
  db:
    image: postgres
    container_name: database
    restart: always
    environment:
      - "POSTGRES_PASSWORD=postgresPass"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=postgres"
    ports:
      - 5432:5432
    volumes:
      - type: volume
        source: database-data
        target: /var/lib/postgresql/data
  backend:
    build: ./wtd-backend
    container_name: backend
    restart: always
    ports:
      - "1234:8000"
    environment:
      - "USER_EMAIL=support@pubbles.app"
      - "USER_EMAIL_PASSWORD=PubblesP@$$$$w0rdSupport"
      - "database=postgres"
      - "username=postgres"
      - "password=postgresPass"
    volumes:
      - type: volume
        source: django-static
        target: /code/static
      - type: volume
        source: django-uploads
        target: /code/media/
    links:
      - redis
    depends_on:
      - db
  redis:
    image: "redis:alpine"
    restart: always
    ports:
        - "6379:6379"
volumes:
  django-static:
  django-uploads:
  database-data: