"""
Django settings for wtd project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from decimal import Decimal
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'q1(lqb4(qh1gje2p=@@bo4oh-2nek9_mnxujpc71^c@d2#s8r6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
CORS_ORIGIN_ALLOW_ALL = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework.authtoken',
    'rest_framework',
    # 'django_otp',
    # 'django_otp.plugins.otp_totp',
    # 'django_otp.plugins.otp_static',
    # 'drf_yasg',
    # 'polymorphic',
    'constance',
    'accounts',
    'orders.apps.OrdersConfig',
    'otp.apps.OtpConfig',
    # 'channels',
    'simple_history',
    'payments',
    'constance.backends.database',
]

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASSES':
        'rest_framework.pagination.PageNumberPagination',
        'PAGE_SIZE': 30,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.BasicAuthentication',  # To be removed later
        'rest_framework.authentication.SessionAuthentication',
    ]


}

AUTHENTICATION_BACKENDS = (
    ('django.contrib.auth.backends.ModelBackend'),
)

CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'

CONSTANCE_CONFIG = {
    'STARTING_PRICE': (200, 'Price to start trip when using WTD Equation', int),
    'KILO_PRICE': (5, 'Price of Kilometer when using WTD Equation', int),
    'MINUTE_PRICE':   (3, 'Price of Minute when using WTD Equation', int),
    'WAITING_PRICE': (50, 'Price of HOUR when using WTD Equation and WAITING', int),
    'ROUND_TRIP_RATIO': (1.5, 'The ratio (Multiple) of 2 way trip', float),
    'PICKUP_SEARCH_RADIUS':  (40, 'When Auto Assigning order to provider, this is the radius of the circle to search for organizations', int),
    'ALLOW_SMS_SYSTEM':  (True, 'If Value unchecked, No SMS Notifications will be sent to anyone', bool),
    'PICKUP_DROPOFF_OPERATION_IN_MINUTES': (20, 'Average time of operation to PickUp/DropOff client', int),

    'SMS_CLIENT_NEW_ORDER_AR': ('تم استلامه و في انتظار الموافقة', 'SMS sent to client when paying', str),
    'SMS_CLIENT_NEW_ORDER_EN': ('has been created, waiting for approval', 'SMS sent to client when paying', str),

    'SMS_OPERATION_NEW_ORDER_AR': ('تم انشاؤه', 'SMS sent to operation when client pays', str),
    'SMS_OPERATION_NEW_ORDER_EN': ('has been created', 'SMS sent to operation when client pays', str),

    'SMS_PROVIDER_RECEIVE_ORDER_AR': ('تم ارساله إليك من قبل وتد، رجاء تحديث الصفحة و من ثم القبول أو الرفض', 'SMS sent to provider when new order is received', str),
    'SMS_PROVIDER_RECEIVE_ORDER_EN': ('has been sent to you by Wtd, please refresh your page, then approve or decline', 'SMS sent to provider when new order is received', str),

    'SMS_OPERATION_PROVIDER_REJECTED_AR': ('تم رفضه', 'SMS sent to operation when a provider rejects an order', str),
    'SMS_OPERATION_PROVIDER_REJECTED_EN': ('has been rejected', 'SMS sent to operation when a provider rejects an order', str),

    'SMS_OPERATION_PROVIDER_ACCEPTED_AR': ('تمت الموافقة عليه و جدولته', 'SMS sent to operation when a provider accepts an order', str),
    'SMS_OPERATION_PROVIDER_ACCEPTED_EN': ('has been approved and scheduled', 'SMS sent to operation when a provider accepts an order', str),

    'SMS_CLIENT_ORDER_APPROVED_AR': ('تمت الموافقة عليه و جدولته', 'SMS sent to client when a provider accepts an order', str),
    'SMS_CLIENT_ORDER_APPROVED_EN': ('has been approved and scheduled', 'SMS sent to client when a provider accepts an order', str),

    'SMS_OPERATION_PROVIDER_STARTED_AR': ('بدأ من قبل مقدم الخدمة', 'SMS sent to operation when a provider starts an order', str),
    'SMS_OPERATION_PROVIDER_STARTED_EN': ('has been started by provider', 'SMS sent to operation when a provider starts an order', str),

    'SMS_CLIENT_PROVIDER_STARTED_AR': ('، سيارة الاسعاف في طريقها إليك', 'SMS sent to client when a provider starts an order', str),
    'SMS_CLIENT_PROVIDER_STARTED_EN': ('has been started, an ambulance is on its way to you', 'SMS sent to client when a provider starts an order', str),

    'SMS_CLIENT_ORDER_CANCELLED_AR': ('تم إلغاؤه', 'SMS sent to client when an order is cancelled', str),
    'SMS_CLIENT_ORDER_CANCELLED_EN': ('has been canceled', 'SMS sent to client when an order is cancelled', str),

    'SMS_PROVIDER_ORDER_CANCELLED_AR': ('تم إلغاؤه', 'SMS sent to provider when an order is cancelled', str),
    'SMS_PROVIDER_ORDER_CANCELLED_EN': ('has been canceled', 'SMS sent to provider when an order is cancelled', str),

    'SMS_CLIENT_ORDER_DONE_AR': ('تم الانتهاء منه', 'SMS sent to client when an order is done', str),
    'SMS_CLIENT_ORDER_DONE_EN': ('has been completed', 'SMS sent to client when an order is done', str),

    'SMS_OPERATION_ORDER_DONE_AR': ('تم الانتهاء منه', 'SMS sent to operation when an order is done', str),
    'SMS_OPERATION_ORDER_DONE_EN': ('has been completed', 'SMS sent to operation when an order is done', str),

    'SMS_OPERATION_NO_AUTO_ASSIGN_AR': ('يتطلب تعيين مقدم الخدمة يدويًا', 'SMS sent to operation when system cannot send order to Provider Automatically', str),
    'SMS_OPERATION_NO_AUTO_ASSIGN_EN': ('must be assigned manually', 'SMS sent to operation when system cannot send order to Provider Automatically', str),



    'SMS_OPERATION_AUTO_ASSIGN_AR': ('تم دفعه وتعيينه لمقدم خدمة', 'SMS sent to operation when system cannot send order to Provider Automatically', str),
    'SMS_OPERATION_AUTO_ASSIGN_EN': ('has been paid for and assigned to provider', 'SMS sent to operation when system cannot send order to Provider Automatically', str),


}

# from constance import config
# getattr(config, 'ACCELERATOR_ACTIVE')

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]

ROOT_URLCONF = 'wtd.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wtd.wsgi.application'
# ASGI_APPLICATION = 'wtd.asgi.application'
# ASGI_APPLICATION = "wtd.routing.application"
# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels_redis.core.RedisChannelLayer',
#         'CONFIG': {
#             # "hosts": [('127.0.0.1', 6379)],
#             "hosts": [("redis", 6379)],
#         },
#     },
# }

CELERY_BROKER_URL = 'redis://localhost:6379'
CELERY_BEAT_SCHEDULE = {
    'delete_expired_otp': {
        'task': 'otp.tasks.otp_handle',
        'schedule': float(os.getenv('CELERY_BEAT_SCHEDULE', '30.0')),
    },
    'delete_inactive_users': {
        'task': 'otp.tasks.inActive_users_handle',
        'schedule': float(os.getenv('CELERY_BEAT_SCHEDULE', '5.0')),
    }
}

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = os.getenv('USER_EMAIL', 'pbblsspprt@gmail.com')
EMAIL_HOST_PASSWORD = os.getenv('USER_EMAIL_PASSWORD', 'QAZqaz@123')
# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

#

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'defaultdb',
        'USER': 'doadmin',
        'PASSWORD': 'vwhQkTCyZoZ81FUg',
        'HOST': 'db-postgresql-fra1-45029-do-user-8981715-0.b.db.ondigitalocean.com',
        'PORT': '25060',
    }
}
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.getenv('database', 'defaultdb'),
#         'USER': os.getenv('username', 'doadmin'),
#         'PASSWORD': os.getenv('password', 'vwhQkTCyZoZ81FUg'),
#         'HOST': os.getenv('host', 'db-postgresql-fra1-45029-do-user-8981715-0.b.db.ondigitalocean.com'),
#         'PORT': os.getenv('port', '25060'),
#     }
# }
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
AWS_ACCESS_KEY_ID = 'SGBGPFRADB4OLGNOKLPL'
AWS_STORAGE_BUCKET_NAME = 'wtd-space'
AWS_SECRET_ACCESS_KEY = 'irRJV3bQdNM6KFtTBniCpX1fU7jdaj5m3Ay1Y/tzfHY'
AWS_S3_REGION_NAME = 'fra1'
AWS_S3_ENDPOINT_URL = 'https://fra1.digitaloceanspaces.com'
AWS_S3_FILE_OVERWRITE = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

# STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
AUTH_USER_MODEL = 'accounts.User'