# Generated by Django 3.1 on 2022-03-23 10:37

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('percentage', models.IntegerField(default=70)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialAccounts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '555555555'. Up to 9 digits allowed.", regex='^(5)(5|0|3|6|4|9|1|8|7)([0-9]{7})$')], verbose_name='special phone number')),
            ],
        ),
        migrations.AddField(
            model_name='operationprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_providers', to='accounts.organization'),
        ),
    ]
