# Generated by Django 3.1 on 2022-03-23 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220323_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerprofile',
            name='approval',
        ),
    ]
