# Generated by Django 3.1 on 2021-01-29 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210129_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerprofile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_providers', to='accounts.organization'),
        ),
    ]
