# Generated by Django 3.1 on 2021-03-07 10:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210129_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='location',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
