# Generated by Django 3.1 on 2021-06-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_organization_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
