# Generated by Django 3.1 on 2021-09-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_operationprofile_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='percentage',
            field=models.IntegerField(default=70),
        ),
    ]
