# Generated by Django 3.1 on 2021-09-20 20:41

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_organization_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialAccounts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '555555555'. Up to 9 digits allowed.", regex='^(5)(5|0|3|6|4|9|1|8|7)([0-9]{7})$')], verbose_name='special phone number')),
            ],
        ),
    ]
