# -*- coding: utf-8 -*-

"""
    unifonicnextgen

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

from unifonicnextgen.api_helper import APIHelper


class Configuration(object):

    """A class used for configuring the SDK by a user.

    This class need not be instantiated and all properties and methods
    are accessible without instance creation.

    """

    # Set the array parameter serialization method
    # (allowed: indexed, unindexed, plain, csv, tsv, psv)
    array_serialization = "indexed"

    # An enum for SDK environments
    class Environment(object):
        # Describe the setting where software and other products are actually put into operation for their intended uses by end users
        PRODUCTION = 0

    # An enum for API servers
    class Server(object):
        BASE_URL = 0

    # The environment in which the SDK is running
    environment = Environment.PRODUCTION

    # The username to use with basic authentication
    # TODO: Set an appropriate value
    basic_auth_user_name = None

    # The password to use with basic authentication
    # TODO: Set an appropriate value
    basic_auth_password = None


    # All the environments the SDK can run in
    environments = {
        Environment.PRODUCTION: {
            Server.BASE_URL: 'http://basic.unifonic.com',
        },
    }

    @classmethod
    def get_base_uri(cls, server=Server.BASE_URL):
        """Generates the appropriate base URI for the environment and the server.

        Args:
            server (Configuration.Server): The server enum for which the base URI is required.

        Returns:
            String: The base URI.

        """
        return cls.environments[cls.environment][server]
