# -*- coding: utf-8 -*-

"""
    unifonicnextgen

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

from unifonicnextgen.decorators import lazy_property
from unifonicnextgen.configuration import Configuration
from unifonicnextgen.controllers.wrapper_controller import WrapperController
from unifonicnextgen.controllers.rest_controller import RestController


class UnifonicnextgenClient(object):

    config = Configuration

    @lazy_property
    def wrapper(self):
        return WrapperController()

    @lazy_property
    def rest(self):
        return RestController()


    def __init__(self,
                 basic_auth_user_name=None,
                 basic_auth_password=None):
        if basic_auth_user_name is not None:
            Configuration.basic_auth_user_name = basic_auth_user_name
        if basic_auth_password is not None:
            Configuration.basic_auth_password = basic_auth_password

