# Generated by Django 3.1 on 2022-11-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='is_approved_by_operation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_approved_by_operation',
            field=models.BooleanField(default=False),
        ),
    ]
