# Generated by Django 3.1 on 2022-03-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20220131_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='is_emergency',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_emergency',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
