# Generated by Django 3.1 on 2022-03-27 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_providerprofile_approval'),
        ('orders', '0002_auto_20220323_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPossibleProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_possible_providers', to='orders.order')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_possible_orders', to='accounts.providerprofile')),
            ],
        ),
    ]
