# Generated by Django 3.1 on 2022-01-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20220125_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='discharge_approval',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='is_contagious',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='is_discharged',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='is_overweight',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='needs_oxygen',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='discharge_approval',
            field=models.FileField(blank=True, null=True, upload_to='discharge_approvals'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_contagious',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_discharged',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_overweight',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='needs_oxygen',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
