# Generated by Django 3.1 on 2022-01-25 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_specialaccounts'),
        ('orders', '0002_auto_20220124_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='operator',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.operationprofile'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='initial_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operator_related_orders', to='accounts.operationprofile'),
        ),
    ]
