# Generated by Django 3.1 on 2021-01-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='distance',
            new_name='distance_value',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='duration',
            new_name='duration_value',
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='approved_by_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='distance_text',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='duration_text',
            field=models.CharField(default='f', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='approved_by_client',
            field=models.BooleanField(default=False),
        ),
    ]
