# Generated by Django 3.1 on 2022-01-29 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_specialaccounts'),
        ('orders', '0003_auto_20220125_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='operator',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.operationprofile'),
        ),
        migrations.AddField(
            model_name='order',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operator_related_orders', to='accounts.operationprofile'),
        ),
        migrations.AddField(
            model_name='speciallocation',
            name='special_price',
            field=models.IntegerField(default=0),
        ),
    ]
