# Generated by Django 3.1 on 2022-01-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20220125_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciallocation',
            name='special_price',
            field=models.IntegerField(default=0),
        ),
    ]
