# Generated by Django 3.1 on 2021-01-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210111_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='need_nurse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='need_nurse',
            field=models.BooleanField(default=False),
        ),
    ]
