# Generated by Django 3.1 on 2021-01-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_extraservices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraservices',
            name='order',
        ),
        migrations.AddField(
            model_name='extraservices',
            name='order',
            field=models.ManyToManyField(blank=True, null=True, related_name='ordr_extra_services', to='orders.Order'),
        ),
    ]
