# Generated by Django 3.1 on 2021-01-24 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210124_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraservices',
            name='order',
        ),
    ]
