# Generated by Django 3.1 on 2021-02-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20210129_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
