# Generated by Django 3.1 on 2021-06-12 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20210201_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorder',
            name='need_nurse',
        ),
        migrations.RemoveField(
            model_name='order',
            name='need_nurse',
        ),
    ]
