# Generated by Django 3.1 on 2021-06-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20210612_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='special_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='special_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
