# Generated by Django 3.1 on 2021-06-25 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20210625_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorder',
            name='special_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='special_id',
        ),
    ]
