# Generated by Django 3.1 on 2021-07-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20210625_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='payment_authorized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_authorized',
            field=models.BooleanField(default=False),
        ),
    ]
