# Generated by Django 3.1 on 2021-09-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20210906_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='order_type',
            field=models.CharField(default='ONE_WAY', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='waiting_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(default='ONE_WAY', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='waiting_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
