# Generated by Django 3.1 on 2022-01-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20210920_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='initial_cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
